// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refreshTokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefeshToken = `-- name: CreateRefeshToken :exec
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at, revoked_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    null
)
`

type CreateRefeshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateRefeshToken(ctx context.Context, arg CreateRefeshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefeshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}
